'use client';

import { useState } from 'react';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { AlertCircle, FileText, Check, BrainCircuit, Code, Server, Database } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';

export default function Home() {
  const [text, setText] = useState('');
  const [result, setResult] = useState<null | {
    result: string;
    ai_probability: number;
    ai_percentage: number;
    stats: {
      word_count: number;
      character_count: number;
    }
  }>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const analyzeText = async () => {
    if (!text.trim()) {
      setError('Please enter some text to analyze');
      return;
    }

    setLoading(true);
    setError(null);
    
    try {
      console.log('Sending request with text:', text.substring(0, 100) + '...');
      // Use the Next.js API route as a proxy
      const response = await fetch('/api/detect', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ text }),
      });
      
      if (!response.ok) {
        const errorText = await response.text();
        console.error(`Server response: ${response.status} ${response.statusText}`, errorText);
        throw new Error(`Failed to analyze text: ${response.status} ${response.statusText}`);
      }
      
      const data = await response.json();
      setResult(data);
    } catch (err) {
      setError('Error connecting to the server. Make sure the backend is running.');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="container mx-auto py-8 px-4 max-w-4xl">
      <h1 className="text-3xl font-bold text-center mb-2">AI Text Detector</h1>
      <p className="text-center text-muted-foreground mb-8">
        Analyze text to determine if it was written by a human or generated by AI. Final Project by Christopher K for CS4200.
      </p>

      {error && (
        <Alert variant="destructive" className="mb-6">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Error</AlertTitle>
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      <Card className="mb-8">
        <CardHeader>
          <CardTitle>Text Analysis</CardTitle>
          <CardDescription>
            Paste your text below to analyze it
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Textarea
            placeholder="Enter or paste text here..."
            className="min-h-[200px] mb-4"
            value={text}
            onChange={(e) => setText(e.target.value)}
          />
        </CardContent>
        <CardFooter className="flex justify-end">
          <Button 
            onClick={analyzeText} 
            disabled={loading || !text.trim()}
          >
            {loading ? 'Analyzing...' : 'Analyze Text'}
          </Button>
        </CardFooter>
      </Card>

      {result && (
        <Card className="mb-8">
          <CardHeader>
            <CardTitle>Analysis Results</CardTitle>
            <CardDescription>
              Our AI model has analyzed your text
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <h3 className="text-lg font-medium">Classification</h3>
                <span className={`px-3 py-1 rounded-full text-sm font-medium ${
                  result.result === "AI-generated" 
                    ? "bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-500"
                    : "bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-500"
                }`}>
                  {result.result === "AI-generated" ? (
                    <span className="flex items-center gap-1">
                      <AlertCircle className="h-4 w-4" />
                      AI-Generated
                    </span>
                  ) : (
                    <span className="flex items-center gap-1">
                      <Check className="h-4 w-4" />
                      Human-Written
                    </span>
                  )}
                </span>
              </div>
              <div className="space-y-1">
                <div className="flex justify-between text-sm">
                  <span>Human</span>
                  <span>AI</span>
                </div>
                <Progress 
                  value={result.ai_percentage} 
                  className="h-2" 
                />
                <div className="flex justify-end text-sm font-medium">
                  {result.ai_percentage}% likely to be AI-generated
                </div>
              </div>
            </div>

            <div className="pt-4 border-t">
              <h3 className="text-lg font-medium mb-3">Text Statistics</h3>
              <div className="grid grid-cols-2 gap-4">
                <div className="bg-secondary rounded-lg p-4 flex items-center gap-3">
                  <FileText className="h-5 w-5 text-primary" />
                  <div>
                    <p className="text-sm text-muted-foreground">Word Count</p>
                    <p className="text-lg font-medium">{result.stats.word_count}</p>
                  </div>
                </div>
                <div className="bg-secondary rounded-lg p-4 flex items-center gap-3">
                  <FileText className="h-5 w-5 text-primary" />
                  <div>
                    <p className="text-sm text-muted-foreground">Character Count</p>
                    <p className="text-lg font-medium">{result.stats.character_count}</p>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Project Technologies & Development Section */}
      <Card>
        <CardHeader>
          <CardTitle>About This Project</CardTitle>
          <CardDescription>
            How this AI Text Detector works and the technologies behind it
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-4">
            <h3 className="text-lg font-medium flex items-center gap-2">
              <BrainCircuit className="h-5 w-5 text-primary" />
              Machine Learning Model
            </h3>
            <p className="text-muted-foreground">
              This application uses DistilBERT, a lightweight variant of BERT (Bidirectional Encoder Representations from Transformers), to analyze and classify text. The model was fine-tuned on a dataset of 5,000 human-written and AI-generated texts to achieve over 99% accuracy on validation data.
            </p>
            <p className="text-muted-foreground">
              For longer texts, we implement a sliding window approach that breaks the content into overlapping chunks of 256 tokens, processes each individually, and then averages the results for a comprehensive analysis.
            </p>
          </div>

          <div className="space-y-4">
            <h3 className="text-lg font-medium flex items-center gap-2">
              <Server className="h-5 w-5 text-primary" />
              Backend Architecture
            </h3>
            <p className="text-muted-foreground">
              The backend is built with Flask, a lightweight Python web framework, and integrates with HuggingFace's Transformers library to provide ML capabilities. The server exposes REST API endpoints for text analysis and health monitoring.
            </p>
            <p className="text-muted-foreground">
              Key components include:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
              <li>Flask for API routing</li>
              <li>HuggingFace Transformers for ML model hosting</li>
              <li>PyTorch as the underlying ML framework</li>
              <li>Flask-CORS for handling cross-origin requests</li>
            </ul>
          </div>

          <div className="space-y-4">
            <h3 className="text-lg font-medium flex items-center gap-2">
              <Code className="h-5 w-5 text-primary" />
              Frontend Implementation
            </h3>
            <p className="text-muted-foreground">
              The frontend is built with Next.js and modern React patterns, featuring a clean UI powered by Tailwind CSS and shadcn/ui components. It includes real-time feedback, error handling, and a responsive design.
            </p>
            <p className="text-muted-foreground">
              Key technologies:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
              <li>Next.js for React framework and API routing</li>
              <li>TypeScript for type safety</li>
              <li>Tailwind CSS for utility-first styling</li>
              <li>shadcn/ui for high-quality UI components</li>
              <li>Lucide React for beautiful icons</li>
            </ul>
          </div>

          <div className="space-y-4">
            <h3 className="text-lg font-medium flex items-center gap-2">
              <Database className="h-5 w-5 text-primary" />
              Data Flow
            </h3>
            <p className="text-muted-foreground">
              When you submit text for analysis, the following process occurs:
            </p>
            <ol className="list-decimal list-inside text-muted-foreground space-y-1 ml-4">
              <li>Your text is sent from the browser to a Next.js API route</li>
              <li>The API route forwards the request to the Flask backend</li>
              <li>The backend processes the text through the DistilBERT model</li>
              <li>The model calculates an AI probability score using softmax</li>
              <li>Results are returned to the frontend and displayed in the UI</li>
            </ol>
            <p className="text-muted-foreground mt-4">
              This architecture solves cross-origin issues by using server-side proxy communication between the Next.js server and Flask backend.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}